web:
  image: 'gitlab/gitlab-ce:latest'
  restart: 'no'
  hostname: 'scm'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://scm.ascii.in.th:8080'

      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '8080:80'
    - '9022:22'
  volumes:
    - '/home/nc-user/Docker/gitlab-ce/config:/etc/gitlab'
    - '/home/nc-user/Docker/gitlab-ce/logs:/var/log/gitlab'
    - '/home/nc-user/Docker/gitlab-ce/data:/var/opt/gitlab'
