web:
  image: 'gitlab-ce:latest'
  restart: 'no'
  hostname: 'ascii'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://192.168.1.109'

      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '9080:80'
    - '9022:22'
  volumes:
    - '/home/nutt/Docker/gitlab-ce/config:/etc/gitlab'
    - '/home/nutt/Docker/gitlab-ce/logs:/var/log/gitlab'
    - '/home/nutt/Docker/gitlab-ce/data:/var/opt/gitlab'
